# Generated by Django 4.1.6 on 2023-02-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_desktop_discount_alter_notebook_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='bluetooth',
            field=models.BooleanField(default=True, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='rgb',
            field=models.BooleanField(default=True, verbose_name='Подсветка'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='wifi',
            field=models.BooleanField(default=True, verbose_name='Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='bluetooth',
            field=models.BooleanField(default=True, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='rgb',
            field=models.BooleanField(default=True, verbose_name='Подсветка'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='web_cam',
            field=models.BooleanField(default=True, verbose_name='Веб-камера'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='wifi',
            field=models.BooleanField(default=True, verbose_name='Wi-Fi'),
        ),
    ]
